### ISSUE TITLE
Extract `config/routes/sidekiq.rb`

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto_commons#8]
Can we try to move this https://github.com/bigbinary/neeto-codify-web/blob/master/config/routes/sidekiq.rb to neeto commons?

Pretty much every app uses sidekiq with the same config.

**Comment by unnitallman** [comment]
Let us add a `routes` folder in commons. We can straightaway move `sidekiq.rb` and `devise.rb` into it. 
Also there is `draw` method defined in all repos. Let us move that also to commons. `routes/draw.rb`

So that in the routes.rb of the apps we will have 

`NeetoCommons::Routes.draw :sidekiq`
`NeetoCommons::Routes.draw :devise`

etc.
